#!/bin/bash

echo "--------- Firmware Update Builder ---------"
echo "This program will pack the home folder."
echo "=== IMPORTANT ==="
echo "Don't forget to place a script with the name of the firmware update in the github script repository (~/ism-device-scripts/fw-settings-scripts/)"
echo "This has to be done before executing the firmware update. The devices will pull the changes from origin."
cd /home/debian

echo -n "Compressing home folder..."
# Create compressed tarball of all non hidden files and folders
tar -czf home.tgz *
echo -ne "Done\nCreating archive..."
tar -cf update.tar home.tgz -C ism-device-scripts/files/fwupdate apply.sh
echo -ne "Done\nRemoving leftover files..."
rm home.tgz
echo -e "Done!\nCreated file update.tar in /home/debian"
