#!/bin/bash

echo "--------- Firmware Update Builder ---------"
echo "This will build a firmware update file to be uploaded to the portal."
echo "This program will pack the home folder and some scripts to apply the firmware update in one tarfile."
echo "Please place a settings script called settings.sh in /home/debian"
echo "To continue, press any key. To exit, press ctrl+c "
read t
cd /home/debian
chmod +x /home/debian/settings.sh
mv /home/debian/settings.sh /home/debian/.ismdata
echo -n "Compressing home folder..."
# Create compressed tarball of all non hidden files and folders
tar -czf home.tgz *
echo -ne "Done\nCreating archive..."
tar -cf update.tar home.tgz -C ism-device-scripts/files/fwupdate apply.sh -C /home/debian/.ismdata settings.sh
echo -ne "Done\nRemoving leftover files..."
rm home.tgz
rm /home/debian/.ismdata/settings.sh
echo -e "Done!\nCreated file update.tar in /home/debian"
